"""Tests for dispatch_coordinator visualize hook (srs.md -> srs.html)."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_ORCH = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(_ORCH))
_TESTS = Path(__file__).resolve().parent
sys.path.insert(0, str(_TESTS))

from lib.normalized_schema import save_project_model  # noqa: E402
from test_e2e import _build_full_model  # noqa: E402

PYTHON = sys.executable
DISPATCH = _ORCH / "dispatch_coordinator.py"


def _init(tmp_path, *extra):
    model = tmp_path / "pm.json"
    save_project_model(_build_full_model(), model)
    docs = tmp_path / "docs"
    res = subprocess.run(
        [PYTHON, str(DISPATCH), "init", "--project-model", str(model),
         "--outputs", "srs", "--docs-dir", str(docs), *extra],
        capture_output=True, text=True,
    )
    return res, docs


def test_init_visualize_default_creates_srs_html(tmp_path):
    res, docs = _init(tmp_path)
    assert res.returncode == 0, res.stderr
    assert (docs / "srs.md").exists()
    assert (docs / "srs.html").exists(), "srs.html should be generated by default for srs"
    html = (docs / "srs.html").read_text(encoding="utf-8")
    assert "--mor-navy:#0E1A4B" in html
    assert "srs-html" in res.stdout  # StepResult emitted in JSON payload


def test_init_no_visualize_skips_html(tmp_path):
    res, docs = _init(tmp_path, "--no-visualize")
    assert res.returncode == 0, res.stderr
    assert (docs / "srs.md").exists()
    assert not (docs / "srs.html").exists()


def test_run_init_function_visualize_flag(tmp_path):
    """Direct call to run_init honours the visualize kwarg."""
    from dispatch_coordinator import run_init

    model = tmp_path / "pm.json"
    save_project_model(_build_full_model(), model)
    docs = tmp_path / "docs"
    results = run_init(model, "EN", ["srs"], docs, visualize=True)
    names = {r.name for r in results}
    assert "srs-html" in names
    assert (docs / "srs.html").exists()
