#!/usr/bin/env bash
# test-drift-detector.sh — coverage for scripts/check-codex-drift.sh
#
# Cases covered (per Task 2 of codex-fork-skills-clone):
#   1. skills-codex/ missing            → exit 0, friendly "not yet bootstrapped"
#   2. skills-codex/ + baseline + match → exit 0, "no drift detected"
#   3. skills/ source modified vs       → exit 0, WARN on stderr listing file
#      baseline AND skills-codex/ stale
#   4. skills-codex/ exists but         → exit 0, WARN "baseline missing"
#      .drift-baseline missing
#
# All cases use mktemp -d fixtures — no real skills are touched.

set -uo pipefail

TEST_NAME="drift-detector"
HELPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HELPER_DIR/test-helper.sh"

SCRIPT="$TEST_PLUGIN_ROOT/scripts/check-codex-drift.sh"

# Portable sha256 — sha256sum (Linux) or shasum -a 256 (macOS).
sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

# Build a baseline file from a list of source skill paths (relative to $src).
# Format: <relpath>:<sha256>
write_baseline() {
    local baseline="$1" src="$2"
    shift 2
    {
        echo "# drift-baseline — generated by sync script. Lines: <relpath>:<sha256>"
        local rel
        while IFS= read -r f; do
            rel="${f#"$src/"}"
            printf '%s:%s\n' "$rel" "$(sha256_of "$f")"
        done < <(find "$src" -type f -name 'SKILL.md' | sort)
    } > "$baseline"
}

# ---------------------------------------------------------------------------
# Case 1 — skills-codex/ not yet bootstrapped → friendly exit 0
# ---------------------------------------------------------------------------
case_1_not_bootstrapped() {
    local tmp; tmp="$(mktemp -d)"
    local src="$tmp/skills"
    local tgt="$tmp/skills-codex"          # deliberately absent
    local baseline="$tmp/.drift-baseline"
    mkdir -p "$src/foo"
    echo "# Foo skill" > "$src/foo/SKILL.md"
    : > "$baseline"

    local stderr stdout rc
    stdout=$(bash "$SCRIPT" --baseline "$baseline" --source "$src" --target "$tgt" 2>/tmp/drift-err.$$)
    rc=$?
    stderr=$(cat /tmp/drift-err.$$ 2>/dev/null || true)
    rm -f /tmp/drift-err.$$

    assert_equal "$rc" "0" "1. exit 0 when skills-codex/ missing"
    local combined="$stdout
$stderr"
    assert_contains "$combined" "not yet bootstrapped" \
        "1. friendly 'not yet bootstrapped' message"
    rm -rf "$tmp"
}

# ---------------------------------------------------------------------------
# Case 2 — baseline matches, no drift → exit 0, "no drift detected"
# ---------------------------------------------------------------------------
case_2_no_drift() {
    local tmp; tmp="$(mktemp -d)"
    local src="$tmp/skills"
    local tgt="$tmp/skills-codex"
    local baseline="$tmp/.drift-baseline"
    mkdir -p "$src/foo" "$tgt/foo"
    echo "# Foo skill (identical body)" > "$src/foo/SKILL.md"
    echo "# Foo skill (identical body)" > "$tgt/foo/SKILL.md"
    write_baseline "$baseline" "$src"

    local stdout rc
    stdout=$(bash "$SCRIPT" --baseline "$baseline" --source "$src" --target "$tgt" 2>&1)
    rc=$?
    assert_equal "$rc" "0" "2. exit 0 when in-sync"
    assert_contains "$stdout" "no drift detected" "2. 'no drift detected' message"
    rm -rf "$tmp"
}

# ---------------------------------------------------------------------------
# Case 3 — source modified after baseline + skills-codex/ stale → warn
# ---------------------------------------------------------------------------
case_3_drift_warn() {
    local tmp; tmp="$(mktemp -d)"
    local src="$tmp/skills"
    local tgt="$tmp/skills-codex"
    local baseline="$tmp/.drift-baseline"
    mkdir -p "$src/foo" "$tgt/foo"
    echo "# Foo skill (original)" > "$src/foo/SKILL.md"
    echo "# Foo skill (original swapped)" > "$tgt/foo/SKILL.md"
    write_baseline "$baseline" "$src"

    # Bump skills-codex mtime DOWN so it predates the upcoming source edit
    # (touch -t works on both BSD and GNU). Use a clearly older timestamp.
    touch -t 202001010000 "$tgt/foo/SKILL.md"

    # Now modify the source file → hash differs from baseline.
    echo "# Foo skill (MODIFIED)" > "$src/foo/SKILL.md"
    # Ensure source mtime is fresh (now).
    touch "$src/foo/SKILL.md"

    local stderr rc stdout
    stdout=$(bash "$SCRIPT" --baseline "$baseline" --source "$src" --target "$tgt" 2>/tmp/drift-err.$$)
    rc=$?
    stderr=$(cat /tmp/drift-err.$$ 2>/dev/null || true)
    rm -f /tmp/drift-err.$$

    assert_equal "$rc" "0" "3. exit 0 even when drift detected (warn, not fail)"
    assert_contains "$stderr" "WARN" "3. WARN keyword on stderr"
    assert_contains "$stderr" "foo/SKILL.md" "3. offending file listed"
    assert_contains "$stderr" "sync-codex-fork.sh" "3. actionable hint: run sync script"
    rm -rf "$tmp"
}

# ---------------------------------------------------------------------------
# Case 4 — skills-codex/ exists but baseline missing → warn, exit 0
# ---------------------------------------------------------------------------
case_4_baseline_missing() {
    local tmp; tmp="$(mktemp -d)"
    local src="$tmp/skills"
    local tgt="$tmp/skills-codex"
    local baseline="$tmp/.drift-baseline"   # not created
    mkdir -p "$src/foo" "$tgt/foo"
    echo "# Foo skill" > "$src/foo/SKILL.md"
    echo "# Foo skill (swapped)" > "$tgt/foo/SKILL.md"

    local stderr rc stdout
    stdout=$(bash "$SCRIPT" --baseline "$baseline" --source "$src" --target "$tgt" 2>/tmp/drift-err.$$)
    rc=$?
    stderr=$(cat /tmp/drift-err.$$ 2>/dev/null || true)
    rm -f /tmp/drift-err.$$

    assert_equal "$rc" "0" "4. exit 0 even when baseline missing"
    local combined="$stdout
$stderr"
    assert_contains "$combined" "baseline missing" "4. 'baseline missing' message"
    assert_contains "$combined" "sync-codex-fork.sh" "4. actionable hint: run sync script"
    rm -rf "$tmp"
}

# ---------------------------------------------------------------------------
# Case 5 — placeholder baseline (header comment only, no entries) should be
# treated like Case 4 when skills-codex/ exists: warn "baseline missing".
# This protects the empty placeholder we ship in Task 2.
# ---------------------------------------------------------------------------
case_5_placeholder_baseline() {
    local tmp; tmp="$(mktemp -d)"
    local src="$tmp/skills"
    local tgt="$tmp/skills-codex"
    local baseline="$tmp/.drift-baseline"
    mkdir -p "$src/foo" "$tgt/foo"
    echo "# Foo" > "$src/foo/SKILL.md"
    echo "# Foo" > "$tgt/foo/SKILL.md"
    # Comment-only baseline — no hash lines.
    cat > "$baseline" <<'EOF'
# drift-baseline placeholder — populated by sync script
EOF

    local stderr rc stdout
    stdout=$(bash "$SCRIPT" --baseline "$baseline" --source "$src" --target "$tgt" 2>/tmp/drift-err.$$)
    rc=$?
    stderr=$(cat /tmp/drift-err.$$ 2>/dev/null || true)
    rm -f /tmp/drift-err.$$

    assert_equal "$rc" "0" "5. exit 0 on placeholder baseline"
    local combined="$stdout
$stderr"
    assert_contains "$combined" "baseline missing" "5. placeholder treated as missing"
    rm -rf "$tmp"
}

case_1_not_bootstrapped
case_2_no_drift
case_3_drift_warn
case_4_baseline_missing
case_5_placeholder_baseline

exit_with_status
